ID = {"Worldwide": 0,
      "AF": 1,
      "AL": 2,
      "DZ": 3,
      "AD": 5,
      "AO": 6,
      "AI": 7,
      "AG": 9,
      "AR": 10,
      "AM": 11,
      "AW": 12,
      "AT": 14,
      "AZ": 15,
      "BS": 16,
      "BH": 17,
      "BD": 18,
      "BB": 19,
      "BY": 20,
      "BZ": 22,
      "BJ": 23,
      "BM": 24,
      "BO": 26,
      "BA": 27,
      "BW": 28,
      "BV": 29,
      "BR": 30,
      "BN": 31,
      "BG": 32,
      "BF": 33,
      "BI": 34,
      "KH": 35,
      "CM": 36,
      "CV": 38,
      "KY": 39,
      "TD": 41,
      "CL": 42,
      "CN": 43,
      "CC": 45,
      "CO": 46,
      "KM": 47,
      "CG": 48,
      "CK": 49,
      "CR": 50,
      "CI": 51,
      "HR": 52,
      "CU": 53,
      "CY": 54,
      "CZ": 55,
      "DK": 56,
      "DJ": 57,
      "DM": 58,
      "DO": 59,
      "TL": 60,
      "EC": 61,
      "EG": 62,
      "SV": 63,
      "EE": 66,
      "ET": 67,
      "FO": 69,
      "FJ": 70,
      "FI": 71,
      "FR": 72,
      "GF": 73,
      "PF": 74,
      "GA": 75,
      "GM": 76,
      "GE": 77,
      "DE": 78,
      "GH": 79,
      "GR": 81,
      "GD": 83,
      "GP": 84,
      "GT": 86,
      "GN": 87,
      "GY": 88,
      "HT": 89,
      "HN": 90,
      "HK": 91,
      "HU": 92,
      "IS": 93,
      "ID": 94,
      "IQ": 95,
      "IE": 96,
      "IT": 97,
      "JM": 98,
      "JO": 100,
      "KZ": 101,
      "KE": 102,
      "KI": 103,
      "KW": 104,
      "KG": 105,
      "LA": 106,
      "LV": 107,
      "LB": 108,
      "LS": 109,
      "LR": 110,
      "LY": 111,
      "LT": 113,
      "LU": 114,
      "MO": 115,
      "MK": 116,
      "MG": 117,
      "MW": 118,
      "MY": 119,
      "MV": 120,
      "ML": 121,
      "MT": 122,
      "MQ": 124,
      "MR": 125,
      "MU": 126,
      "MX": 128,
      "FM": 129,
      "MD": 130,
      "MC": 131,
      "MN": 132,
      "MA": 134,
      "MZ": 135,
      "MM": 136,
      "NA": 137,
      "NP": 139,
      "NL": 140,
      "AN": 141,
      "NC": 142,
      "NZ": 143,
      "NI": 144,
      "NE": 145,
      "NG": 146,
      "NO": 149,
      "OM": 150,
      "PK": 151,
      "PW": 152,
      "PA": 153,
      "PG": 154,
      "PY": 155,
      "PE": 156,
      "PH": 157,
      "PL": 159,
      "PT": 160,
      "QA": 162,
      "RE": 163,
      "RO": 164,
      "RW": 166,
      "KN": 167,
      "LC": 168,
      "SA": 171,
      "SN": 172,
      "SC": 173,
      "SG": 175,
      "SK": 176,
      "SI": 177,
      "SO": 179,
      "ZA": 180,
      "KR": 181,
      "ES": 182,
      "LK": 183,
      "SH": 184,
      "SR": 186,
      "SZ": 187,
      "SE": 188,
      "CH": 189,
      "TW": 191,
      "TJ": 192,
      "TZ": 193,
      "TH": 194,
      "TG": 195,
      "TT": 198,
      "TN": 199,
      "TR": 200,
      "TM": 201,
      "UG": 203,
      "UA": 204,
      "AE": 205,
      "GB": 206,
      "UY": 207,
      "UZ": 208,
      "VE": 211,
      "VN": 212,
      "VG": 213,
      "YE": 216,
      "ZM": 218,
      "ZW": 219,
      "RS": 220,
      "ME": 221,
      "IN": 225,
      "TC": 234,
      "CD": 235,
      "GG": 236,
      "IM": 237,
      "JE": 239,
      "CW": 246, }

Names = {"AF": "Afeganist\u00e3o", "CL": "Chile", "ZA": "Africa do Sul", "CN": "China", "AL": "Alb\u00e2nia",
         "CY": "Chipre", "DE": "Alemanha", "CO": "Col\u00f4mbia", "AD": "Andorra", "KM": "Comores", "AO": "Angola",
         "CG": "Congo", "AI": "Anguilla", "CI": "Costa do Marfim", "AQ": "Antartica", "CR": "Costa Rica",
         "AG": "Ant\u00edgua e Barbuda", "HR": "Cro\u00e1cia", "AN": "Antilhas Holandesas", "CU": "Cuba",
         "SA": "Ar\u00e1bia Saudita", "DK": "Dinamarca", "DZ": "Arg\u00e9lia", "DJ": "Djibuti", "AR": "Argentina",
         "DM": "Dominica", "AM": "Arm\u00eania", "EG": "Egito", "AW": "Aruba", "SV": "El Salvador",
         "AU": "Austr\u00e1lia", "AE": "Emirados \u00c1rabes Unidos", "AT": "\u00c1ustria", "EC": "Equador",
         "AZ": "Azerbaidj\u00e3o", "ER": "Eritr\u00e9ia", "BS": "Bahamas",
         "EM": "Escrit\u00f3rio para Harmoniza\u00e7\u00e3o no Mercado Interno", "BD": "Bangladesh",
         "SK": "Eslov\u00e1quia", "BB": "Barbados", "SI": "Eslovenia", "BH": "Bareine", "ES": "Espanha",
         "BY": "Belarus", "US": "Estados Unidos da Am\u00e9rica", "BE": "B\u00e9lgica", "EE": "Est\u00f4nia",
         "BZ": "Belize", "ET": "Eti\u00f3pia", "BX": "Benelux", "RU": "Federa\u00e7\u00e3o Russa", "BJ": "Benin",
         "FJ": "Fiji", "BM": "Bermudas", "PH": "Filipinas", "BO": "Bol\u00edvia", "FI": "Finl\u00e2ndia",
         "BA": "B\u00f3snia e Herzeg\u00f3vina", "FR": "Fran\u00e7a", "BW": "Botswana", "GA": "Gab\u00e3o",
         "BR": "Brasil", "GM": "Gambia", "BG": "Bulg\u00e1ria", "GE": "Ge\u00f3rgia", "BN": "Brunei Darussalam",
         "GH": "Gana", "BF": "Burkina Faso", "GS": "Ge\u00f3rgia do Sul e Ilhas Sandwich do Sul", "BI": "Burundi",
         "GI": "Gibraltar", "BT": "But\u00e3o", "GD": "Granada", "CV": "Cabo Verde", "GR": "Gr\u00e9cia",
         "CM": "Camar\u00f5es", "GL": "Groenl\u00e2ndia", "KH": "Camboja", "GP": "Guadalupe", "CA": "Canad\u00e1",
         "GU": "Guam", "QA": "Catar", "GT": "Guatemala", "KZ": "Cazaquist\u00e3o", "GY": "Guiana", "TD": "Chade",
         "GN": "Guine", "GW": "Guin\u00e9 Bissau", "JO": "Jord\u00e2nia", "GQ": "Guine Equatorial", "KI": "Kiribati",
         "HT": "Haiti", "KW": "Kuwait", "NL": "Holanda", "LA": "Laos", "HN": "Honduras", "LS": "Lesoto",
         "HK": "Hong-Kong", "LV": "Let\u00f4nia", "HU": "Hungria", "LB": "L\u00edbano", "YE": "I\u00eamen",
         "LR": "Lib\u00e9ria", "BV": "Ilha Bouvet", "LY": "L\u00edbia", "IM": "Ilha do Homem", "LI": "Liechtenstein",
         "CX": "Ilha Natal", "LT": "Litu\u00e2nia", "NF": "Ilha Norfalk", "LU": "Luxemburgo", "KY": "Ilhas Cayman",
         "MO": "Macau", "CC": "Ilhas Cocos", "MG": "Madagascar", "CK": "Ilhas Cook", "MY": "Mal\u00e1sia",
         "GG": "Ilhas do Canal", "MW": "Malawi", "FO": "Ilhas Faroe", "MV": "Maldivas", "HM": "Ilhas Heard e McDonald",
         "ML": "Mali", "FK": "Ilhas Malvinas", "MT": "Malta", "MP": "Ilhas Marianas do Norte", "MA": "Marrocos",
         "MH": "Ilhas Marshall", "MQ": "Martinica", "UM": "Ilhas Menores", "MU": "Maur\u00edcio",
         "SB": "Ilhas Salom\u00e3o", "MR": "Maurit\u00e2nia", "TC": "Ilhas Turks e Caicos", "MX": "M\u00e9xico",
         "VG": "Ilhas Virgens (Brit\u00e2nicas)", "MM": "Mianm\u00e1", "VI": "Ilhas Virgens (U.S.)",
         "FM": "Micron\u00e9sia", "WF": "Ilhas Wallis e Futura", "MZ": "Mo\u00e7ambique", "IN": "India",
         "MC": "M\u00f4naco", "ID": "Indon\u00e9sia", "MN": "Mong\u00f3lia", "IR": "Ir\u00e3", "MS": "Mont Serrat",
         "IQ": "Iraque", "ME": "Montenegro", "IE": "Irlanda", "NA": "Nam\u00edbia", "IS": "Isl\u00e2ndia",
         "NR": "Nauru", "IL": "Israel", "NP": "Nepal", "NI": "Nicar\u00e1gua", "NE": "N\u00edger", "NG": "Nig\u00e9ria",
         "NO": "Noruega", "NC": "Nova Caled\u00f4nia", "NZ": "Nova Zel\u00e2ndia", "IT": "It\u00e1lia",
         "OM": "Om\u00e3", "JM": "Jamaica", "OA": "Organiza\u00e7\u00e3o Africana de Propriedade Intelectual (OAPI)",
         "JP": "Jap\u00e3o", "WO": "Organiza\u00e7\u00e3o Mundial de Propriedade Intelectual \u2013 OMPI (WIPO)",
         "JE": "Jersey", "AP": "Organiza\u00e7\u00e3o Regional de Propriedade Industrial Africana", "PW": "Palau",
         "SE": "Su\u00e9cia", "PA": "Panam\u00e1", "CH": "Su\u00ed\u00e7a", "PG": "Papua Nova Guin\u00e9",
         "SR": "Suriname", "PK": "Paquist\u00e3o", "SJ": "Svalbard e Jan Mayen", "PY": "Paraguai",
         "TJ": "Tadjiquist\u00e3o", "PE": "Peru", "TH": "Tail\u00e2ndia", "PN": "Pitcairn", "TW": "Taiwan",
         "PF": "Polin\u00e9sia Francesa", "TF": "Terras Austrais Francesas", "PL": "Pol\u00f4nia",
         "IO": "Territ.Britan.Oceano \u00cdndico", "PR": "Porto Rico", "PS": "Territ\u00f3rio Ocupado Palestino",
         "PT": "Portugal", "TL": "Timor-Leste", "KE": "Qu\u00eania", "TG": "Togo", "KG": "Quirguist\u00e3o",
         "TK": "Tokelau", "GB": "Reino Unido", "TO": "Tonga", "CF": "Rep\u00fablica Centro Africana",
         "TT": "Trinidad e Tobago", "KR": "Rep\u00fablica da Cor\u00e9ia", "TN": "Tun\u00edsia",
         "MK": "Rep\u00fablica da Macedonia", "TM": "Turcomenist\u00e3o", "MD": "Rep\u00fablica da Moldova",
         "TR": "Turquia", "CD": "Rep\u00fablica Dem. Do Congo", "TV": "Tuvalu", "DO": "Rep\u00fablica Dominicana",
         "UA": "Ucr\u00e2nia", "KP": "Rep\u00fablica Pop. Dem. da Coreia", "UG": "Uganda",
         "CZ": "Rep\u00fablica Tcheca", "UY": "Uruguai", "TZ": "Rep\u00fablica Unida da Tanz\u00e2nia",
         "UZ": "Uzbequist\u00e3o", "RE": "Reuni\u00e3o", "VU": "Vanuatu", "RO": "Rom\u00eania", "VA": "Vaticano",
         "RW": "Ruanda", "VE": "Venezuela", "EH": "Saara Ocidental", "VN": "Vietn\u00e3",
         "PM": "Saint Pierre e Miquelon", "YU": "Yugosl\u00e1via", "AS": "Samoa Americana", "ZR": "Zaire",
         "WS": "Samoa Ocidental", "ZM": "Z\u00e2mbia", "SH": "Santa Helena", "ZW": "Zimb\u00e1bue",
         "LC": "Santa L\u00facia", "KN": "S\u00e3o Cristov\u00e3o e Nevis", "SM": "S\u00e3o Marino",
         "ST": "S\u00e3o Tom\u00e9 e Pr\u00edncipe", "VC": "S\u00e3o Vicente e Granadinas", "SN": "Senegal",
         "SL": "Serra Leoa", "RS": "S\u00e9rvia", "SC": "Seychelles", "SG": "Singapura", "SY": "S\u00edria",
         "SO": "Som\u00e1lia", "LK": "Sri Lanka", "SZ": "Suazil\u00e2ndia", "SD": "Sud\u00e3o"}
